Storage Drives code is committed in Development branch.
Aliza05/Storage-Drive pull request #1
Opened 2022-11-24 18:30 UTC by Aliza05

2022-11-25 10:47 UTC, hatim523 requested changes
Aliza, have requested some changes in the code, please let me know if you need any help with it.
Thanks :)

2022-11-25 10:47 UTC, hatim523 commented on main.py
> +'''
Missing eof.

2022-11-25 10:47 UTC, hatim523 commented on quickstart.py
> +    main()
Why do we have two `main` entry points in a single program?

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +        flow = oauth2client.client.flow_from_clientsecrets(
Shouldn't the variables needed for initializing `client` reside in the constructor of the class.

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +        drive_service = build('drive', 'v2', http=http)
Service should only be built once and used as an attribute in different class methods.

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +            creds = Credentials.from_authorized_user_file('token.json', SCOPES)
Redundant code to build the same service every time.

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +    if __name__ == '__main__':
`main` should not be here since this file should only contain the class code.

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +#!/usr/bin/python
Remove these comments if they are not adding any value to the code below.

2022-11-25 10:47 UTC, hatim523 commented on googledrive.py
> +SCOPES1 = ['https://www.googleapis.com/auth/drive.readonly']
How is `SCOPES1` different from `SCOPES`?
What is the difference between these two scopes? Variable names should be self-sufficient in defining their usage.

2022-11-25 10:47 UTC, hatim523 commented on main.py
> +from __future__ import print_function
Remove this if not needed.

2022-11-25 10:47 UTC, hatim523 commented on storagedrive.py
> +    def upload(self):
`upload` function should define an argument such as filename etc, which should be the basis for input for it's derived classes.

2022-11-25 10:47 UTC, hatim523 commented on storagedrive.py
> +    def upload(self):
Similarly for `download` and `search` function.

2022-11-29 20:59 UTC, closed without merging

2022-11-29 20:59 UTC, Aliza05 commented
Creating New pull request.